#!/usr/bin/env bash
set -euo pipefail
mkdir -p  $ACTIONS_CACHE_BIN_DIR \
          $RUNNER_TEMPDIR

url=$1
software=$(basename "$url")

if ! command -v "$software" &> /dev/null; then
  echo "𐄂 $software is not installed, downloading ..."
  wget -O $ACTIONS_CACHE_BIN_DIR/$software -q -nv --content-disposition "$url"
  chmod +x $ACTIONS_CACHE_BIN_DIR/$software 2> /dev/null || true
else
  printf "%-35s %s\n" "✔ $software is already installed. " "[ `command -v $software` ]"
fi

$software --version 2>&1 | head -n 1 >> $RUNNER_TEMPDIR/download.txt || true

