#!/bin/bash

# Sun Dec  8 20:24:58 GMT 2013
# Wrappers /usr/bin/time.
# Inspired from this blog article : http://www.thegeekstuff.com/2013/10/time-command-format/

# Darren Evans

if [ $# -eq 0 ]; then
  echo "Usage: $0 command <argv>..."
  echo ""
  exit 1
fi

FILE=$(mktemp)

time=$(command -v gtime || command -v /usr/bin/time)
grep=$(command -v ggrep || command -v /usr/bin/grep)

$time -o $FILE -f "
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Time: %es (CPU: %P  Mem: %MKb  IO: %I/%O  User/Kernel: %Us/%Ss)
%C" "$@"

code=$?
# cat $FILE | GREP_COLORS='mt=01;31' ggrep -E --color=always -C 9999 '\d+|\d+\.|\d+s|\d+\%'
cat $FILE | GREP_COLORS='mt=01;31' $grep -E --color=always -C 9999 '[0-9]+\.?s?%?'
exit $code
