#!/usr/bin/env bash

LATEST="abuseipdb-s100.ipv4"

aggregate() {
  local DAYS=$1
  local OUTPUT=$2

  TEMPFILE=$(mktemp)
  echo $TEMPFILE
  cat $LATEST >> $TEMPFILE

  for commit in $(git log --format=format:%H --since="$DAYS days ago" $LATEST); do
    let "i++"
    git show $commit:$LATEST >> $TEMPFILE

    # Optimize in chunks to ensure the tempfile doesn't become HUGE
    if [[ "$i%100" -eq "0" ]]; then
      iprange --print-single-ips $TEMPFILE >| "$TEMPFILE-tmp"
      mv "$TEMPFILE-tmp" $TEMPFILE
    fi
  done

  iprange --print-single-ips $TEMPFILE >| $OUTPUT
  echo "$OUTPUT (`wc -l < $OUTPUT` ip)"
}

aggregate 1 "abuseipdb-s100-1d.ipv4" &
aggregate 3 "abuseipdb-s100-3d.ipv4" &
aggregate 7 "abuseipdb-s100-7d.ipv4" &
aggregate 30 "abuseipdb-s100-30d.ipv4" &
aggregate 9999 "abuseipdb-s100-all.ipv4" &

wait
